#!/usr/bin/env python

from EulerTools import is_square
from gmpy import popcount

# solution if 1+4n is square => n is generated by k*(k+1)
# perfect solution if k = 0 mod 2**i
sols, solsPerfect = 0, 0
k, t = 0, 1
while solsPerfect * 12345 >= sols:
	k += 1
	n = k*(k+1)
	sols += 1
	if n % (2**t) == 0:
		solsPerfect += 1
		t += 1
print n
